services:
  discord-bot:
    build: .
    container_name: discord_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DISCORD_DATA_PATH}:/app/data/qidian
      - ${DISCORD_LOG_PATH}:/app/logs
    environment:
      - TZ=Etc/UTC